// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxwswrmzavsgxsqxaweo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4d3N3cm16YXZzZ3hzcXhhd2VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMzczNTIsImV4cCI6MjA2NjcxMzM1Mn0.cHqqdFNVYSNuXdbW4sM-6Xbt0kmAOOaynUTPSHpHKyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);